name: Commit Approval

# Overview
#   This workflow can be used to manually approve commits to be deployed to production.
#
# How it Works:
#   1. Every commit is automatically marked as Not approved.
#   2. If a commit has passed manual verification, the commit status can be set to approved by manually running the workflow.
#
# Connecting to your project on Vercel:
#   1. Add the Manual Approval GitHub status as a required Promotion Requirement.

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      sha:
        description: 'Commit SHA to approve'
        required: true
        type: string

jobs:
  set-status:
    runs-on: ubuntu-latest
    permissions:
      statuses: write
    steps:
      - name: Set commit status
        uses: actions/github-script@v7
        with:
          script: |
            const isPush = context.eventName === 'push';
            const sha = isPush ? context.sha : context.payload.inputs.sha;
            const state = isPush ? 'failure' : 'success';
            const description = isPush ? 'Not approved' : 'Approved';

            await github.rest.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha,
              state,
              context: 'Manual Approval',
              description,
            });
